//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NombreUsuario { get; set; }
        public string DepartamentoOrigen { get; set; }
        public string DepartamentoDestino { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int Secuencia { get; set; }
        public string Detalle { get; set; }
    }
}
